<?php

function foro_contactenos_menu()
{
    $items['contactenos-foros-economicos'] = array(
    'title' => '',
    'page callback' => 'foro_economicos_contactenos',
    'access arguments' => array('access content'),
    );
    return $items;
}
function foro_economicos_contactenos(){
    $webform = webform_block_view($delta = 'client-form-1');  
    return theme('foro_economicos_contactenos', array('contacto' =>$webform['content']));
}
/**
 * Implements hook_init().
 */
function foro_contactenos_init()
{
    drupal_add_css(drupal_get_path('module', 'foro_contactenos') . '/css/global_foros.css');
    drupal_add_css(drupal_get_path('module', 'foro_contactenos') . '/css/flexslider.css');
}
/**
 * Implementa hook_theme().
 */
function foro_contactenos_theme()
{
    //@todo Pasar tabs.tpl a la carpeta includes
    return array(
        'foro_economicos_contactenos' => array('variables' => array('contacto' => ''), 'template' => 'includes/block-contactenos'), 
        );
}
/**
 * Implementa hook_page_alter().
 */
function foro_contactenos_page_alter(&$page) {
    if (arg(0) == 'contactenos-foros-economicos' || arg(0) == 'contactenos') {      
        unset($page['header']);
        unset($page['help']);
        unset($page['highlighted']);
        unset($page['featured']);
        unset($page['sidebar_second ']);
        unset($page['highlighted']);
        unset($page['sidebar_first']);
    }
}
function foro_contactenos_block_info()
{
    $block['notasDestacadasFlex'] = array(
        'info' => 'Notas destacadas flex',
        'cache' => DRUPAL_NO_CACHE,
    );

    return $block;
}
function foro_contactenos_block_view($delta)
{
    $block = array();
    switch ($delta) {
        case 'notasDestacadasFlex':
            $custom_title = 'Notas destacadas flex';
            $block['subject'] = l($custom_title, '#NOTASDESTACADAS', array(
                'attributes' => array(
                    'class' => array('notas-destacadas-flex', 'active'),
                ),
                'html' => true,
                    ));
            if (theme_get_setting('slideshow_display','multipurpose')){
                $block2 = module_invoke('views', 'block_view', '91c913ec23173e1a796999135f3e00d9');
                $block2=render($block['content']);                
                $block['content'] = '<di class="base-flex">'.$block2.'<div class="clear-1" style="clear:both;"></div></div>';
            }else{
                $block['content'] = '';
            }
            break;
    }

    return $block;
}