<?php

function foro_contactenos_menu()
{
    $items['contactenos-foros-economicos'] = array(
    'title' => '',
    'page callback' => 'foro_economicos_contactenos',
    'access arguments' => array('access content'),
    );
    return $items;
}
function foro_economicos_contactenos(){
    //$form_contacto=drupal_render(drupal_get_form('webform_client_form_1'));
    $webform = webform_block_view($delta = 'client-form-1');  
    return theme('foro_economicos_contactenos', array('contacto' =>$webform['content']));
}
/**
 * Implements hook_init().
 */
function foro_contactenos_init()
{
    
}
/**
 * Implementa hook_theme().
 */
function foro_contactenos_theme()
{
    //@todo Pasar tabs.tpl a la carpeta includes
    return array(
        'foro_economicos_contactenos' => array('variables' => array('contacto' => ''), 'template' => 'includes/block-contactenos'), 
        );
}
/**
 * Implementa hook_page_alter().
 */
function foro_contactenos_page_alter(&$page) {
    dpm(arg(0),"arg");
    dpm($page,"page");
    if (arg(0) == 'contactenos-foros-economicos') {
        unset($page['header']);
        unset($page['help']);
        unset($page['highlighted']);
        unset($page['featured']);
        unset($page['sidebar_second']);
        unset($page['highlighted']);
        unset($page['sidebar_first']);
    }
}